spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

hikari:
  minimum-idle=3
  maximum-pool-size=10
  max-lifetime=30000
  connection-test-query=SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.javaweb.shopping.entity

